title: Galmuri
author: Minseo Lee
email: quiple@quiple.dev
description: 작은 크기에서도 가독성 좋고 균형 있는 한글 비트맵 폰트.
url: https://galmuri.quiple.dev
twitter_username: kuipuru
github_username: quiple
github_reponame: galmuri
copyright_date: 2019-2024
sass:
  style: compressed
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude:
  - galmuri/.github/
  - galmuri/bitsnpicas/
  - galmuri/mkttf/
  - galmuri/src/
  - galmuri/.gitmodules
  - galmuri/.npmignore
  - galmuri/package-lock.json
  - galmuri/package.json
  - galmuri/README.md
fonts:
  - name: Galmuri14
    family: Galmuri14
    style: Regular
    size: 15
  - name: Galmuri11
    family: Galmuri11
    style: Regular
    size: 12
  - name: Galmuri11 Bold
    family: Galmuri11
    style: Bold
    size: 12
  - name: Galmuri11 Condensed
    family: Galmuri11
    style: Condensed
    size: 12
  - name: Galmuri9
    family: Galmuri9
    style: Regular
    size: 10
  - name: Galmuri7
    family: Galmuri7
    style: Regular
    size: 8
  - name: GalmuriMono11
    family: GalmuriMono11
    style: Monospaced
    size: 12
  - name: GalmuriMono9
    family: GalmuriMono9
    style: Monospaced
    size: 10
  - name: GalmuriMono7
    family: GalmuriMono7
    style: Monospaced
    size: 8
showcase:
  - title: "Keylocker"
    author: "Moonana"
    link: 1325040
    type: steam
    file: not-yet.png
  - title: "STONKS-9800"
    author: "TERNOX"
    link: 1539140
    type: steam
    file: 240202.avif
  - title: "미제사건은 끝내야 하니까"
    author: "Somi"
    link: 2676840
    type: steam
    file: 240118.avif
  - title: "VVVVVV"
    author: "Terry Cavanagh"
    link: 70300
    type: steam
    file: 240111-2.png
  - title: "Momodora: Moonlit Farewell"
    author: "Bombservice"
    link: 1747760
    type: steam
    file: 240111.png
  - title: "Coffee Talk Episode 2: Hibiscus & Butterfly"
    author: "Toge Productions"
    link: 1663220
    type: steam
    file: 230420.avif
  - title: "Papers, Please"
    author: "Lucas Pope"
    link: 239030
    type: steam
    file: 221127.png
  - title: "Dungeon Squad"
    author: "GameCoaster"
    link: 1642733080
    type: appstore
    file: 221006.avif
  - title: "Shotgun King: The Final Checkmate"
    author: "PUNKCAKE Delicieux"
    link: 1972440
    type: steam
    file: 220621.avif
  - title: "Monster Sanctuary"
    author: "솔라리어스"
    link: blog.naver.com/ansewo/222702695752
    type: patch
    file: 220507.png
  - title: "NEEDY GIRL OVERDOSE"
    author: "코스믹딜루즈 & quiple"
    link: cosmicdeluge.tistory.com/5
    type: patch
    file: 220220.png
  - title: "Teamfight Manager"
    author: "Team Samoyed"
    link: 1372810
    type: steam
    file: 210302.avif
  - title: "BLUE REVOLVER"
    author: "Sepheille"
    link: steamcommunity.com/sharedfiles/filedetails/?id=2405396574
    type: patch
    file: 210223.avif
  - title: "Duke Dashington Remastered"
    author: "바람 번역단"
    link: blog.naver.com/bleach1491/222196942354
    type: patch
    file: 210105.png
  - title: "Rev"
    author: "바람 번역단"
    link: blog.naver.com/bleach1491/222180900832
    type: patch
    file: 201221.png
  - title: "Alwa's Legacy"
    author: "바람 번역단"
    link: blog.naver.com/bleach1491/222008221688
    type: patch
    file: 200622.png
  - title: "Westerado: Double Barreled"
    author: "바람 번역단"
    link: blog.naver.com/bleach1491/221820971383
    type: patch
    file: 200223.png
