title: Galmuri
author: Minseo Lee
email: itoupluk427@gmail.com
description: 작은 크기에서도 가독성 좋고 균형 있는 한글 비트맵 폰트.
url: https://galmuri.quiple.dev
twitter_username: kuipuru
github_username: quiple
github_reponame: galmuri
sass:
  style: compressed
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude:
  - galmuri/.github/
  - galmuri/bitsnpicas/
  - galmuri/files/
  - galmuri/mkttf/
  - galmuri/src/
  - galmuri/.gitmodules
  - galmuri/.npmignore
  - galmuri/package-lock.json
  - galmuri/package.json
  - galmuri/README.md
fonts:
  - name: Galmuri14
    file: Galmuri14
    family: Galmuri14
    style: Regular
  - name: Galmuri11
    file: Galmuri11
    family: Galmuri11
    style: Regular
  - name: Galmuri11 Bold
    file: Galmuri11-Bold
    family: Galmuri11
    style: Bold
  - name: Galmuri11 Condensed
    file: Galmuri11-Condensed
    family: Galmuri11
    style: Condensed
  - name: Galmuri9
    file: Galmuri9
    family: Galmuri9
    style: Regular
  - name: Galmuri7
    file: Galmuri7
    family: Galmuri7
    style: Regular
  - name: GalmuriMono11
    file: GalmuriMono11
    family: GalmuriMono11
    style: Monospaced
  - name: GalmuriMono9
    file: GalmuriMono9
    family: GalmuriMono9
    style: Monospaced
  - name: GalmuriMono7
    file: GalmuriMono7
    family: GalmuriMono7
    style: Monospaced
showcase:
  - title: "Keylocker"
    author: "Moonana"
    link: 1325040
    type: steam
    file: not-yet.png
  - title: "Coffee Talk Episode 2: Hibiscus & Butterfly"
    author: "Toge Productions"
    link: 1663220
    type: steam
    file: 230420.png
  - title: "Papers, Please"
    author: "Lucas Pope"
    link: 239030
    type: steam
    file: 221127.png
  - title: "Dungeon Squad"
    author: "GameCoaster"
    link: 1642733080
    type: appstore
    file: 221006.png
  - title: "Shotgun King: The Final Checkmate"
    author: "PUNKCAKE Delicieux"
    link: 1972440
    type: steam
    file: 220621.jpg
  - title: "Monster Sanctuary"
    author: "솔라리어스"
    link: blog.naver.com/ansewo/222702695752
    type: patch
    file: 220507.png
  - title: "NEEDY GIRL OVERDOSE"
    author: "코스믹딜루즈 & Quiple"
    link: cosmicdeluge.tistory.com/5
    type: patch
    file: 220220.png
  - title: "Teamfight Manager"
    author: "Team Samoyed"
    link: 1372810
    type: steam
    file: 210302.jpg
  - title: "BLUE REVOLVER"
    author: "Sepheille"
    link: steamcommunity.com/sharedfiles/filedetails/?id=2405396574
    type: patch
    file: 210223.jpg
  - title: "Duke Dashington Remastered"
    author: "바람 번역단"
    link: blog.naver.com/bleach1491/222196942354
    type: patch
    file: 210105.png
  - title: "Rev"
    author: "바람 번역단"
    link: blog.naver.com/bleach1491/222180900832
    type: patch
    file: 201221.png
  - title: "Alwa's Legacy"
    author: "바람 번역단"
    link: blog.naver.com/bleach1491/222008221688
    type: patch
    file: 200622.png
  - title: "Westerado: Double Barreled"
    author: "바람 번역단"
    link: blog.naver.com/bleach1491/221820971383
    type: patch
    file: 200223.png